version: '3.3'

services:
  bot:
    container_name: bot
    build: .
    command: python3 bot.py
    restart: always
    depends_on:
      - db
    networks:
      - tg_bot
  db:
    container_name: db
    image: onjin/alpine-postgres:9.5
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge
